#!/usr/bin/env sh

get_volume() {
  pactl get-sink-volume @DEFAULT_SINK@ | awk 'NR==1 {print $5}' | sed 's/%//'
}

get_volume
pactl subscribe | while read -r line; do
  case "$line" in
    *"change"*)
      get_volume
      ;;
  esac
done
