#!/usr/bin/env sh

echo ""
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  case "$line" in
    "submap>>"*)
      echo "$line" | awk -F '>>|,' '{print $2}'
      ;;
  esac
done
