#!/usr/bin/env sh

#SINK="@DEFAULT_SINK@"
SINK="virtual-output-control"

get_volume() {
  pactl get-sink-volume "$SINK" | awk 'NR==1 {print $5}' | sed 's/%//'
}

get_volume
pactl subscribe | while read -r line; do
  case "$line" in
    *"change"*)
      get_volume
      ;;
  esac
done
