#!/usr/bin/env sh

find_workspace() {
  hyprctl workspaces -j | jq -c '.[] | select(.name == "'"$1"'")'
}

echo null
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  case "$line" in
    "activespecial>>"*)
      special=`echo "$line" | awk -F'>>|,' '{ print $2}'`
      if [ ! -z "$special" ]; then
        find_workspace "$special"
      else
        echo null
      fi 
      ;;
  esac
done
